### ISSUE TITLE
How to run the code without external MT data?

### ISSUE THREAD

**Issue by XqZeppelinhead0702** [ReneeYe/ConST#8]
Hello, recently I try to train the ConST model without external MT data just to test its performance in this situation and I'm confused about how to regulate the parameters to  achieve this. I think the '--task, --external-parallel-mt-data, --criterion' should be changed but I fail to find the correct candidate for them due to so many choices. I would be extremely grateful if you could give me some guidance. Looking forward to your early reply.

**Comment by ReneeYe** [comment]
> Hello, recently I try to train the ConST model without external MT data just to test its performance in this situation and I'm confused about how to regulate the parameters to achieve this. I think the '--task, --external-parallel-mt-data, --criterion' should be changed but I fail to find the correct candidate for them due to so many choices. I would be extremely grateful if you could give me some guidance. Looking forward to your early reply.

It's been a long time since I last ran the code. If I remember correctly, the code in script/train_en2x.sh also supports WITHOUT external MT dataset, ``--task=speech_to_text_triplet_with_extra_mt`` but leave ``--external-parallel-mt-data`` as none, for criterion, you may use ``label_smoothed_cross_entropy_with_constrastive``.

**Comment by XqZeppelinhead0702** [comment]
Sorry for the late reply because of some personal affairs. Thanks for your reply, that works well for me.
